{
  "formatVersion": "1.1",
  "component": {
    "group": "Alex_Android_Sample",
    "module": "customplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CustomPlugin-1.0.0.jar",
          "url": "CustomPlugin-1.0.0.jar",
          "size": 1556,
          "sha512": "b869ce3aa754cbf91208aeb3faa190052b656cc7f82d5bb6a3b8aa75ee7bc05eadc1beebe989862bbc10d3c7377c3ceade8348c1235d57b578f6217796ab059b",
          "sha256": "8c73241861ccb5259d6717da512cede58c590a8bdcfab882557efb6ddfedf74e",
          "sha1": "a3b979d4b24aa2f9d0b2173ae39fb88568ab9662",
          "md5": "5560e36104c106ee6db87fcab4bb5699"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CustomPlugin-1.0.0.jar",
          "url": "CustomPlugin-1.0.0.jar",
          "size": 1556,
          "sha512": "b869ce3aa754cbf91208aeb3faa190052b656cc7f82d5bb6a3b8aa75ee7bc05eadc1beebe989862bbc10d3c7377c3ceade8348c1235d57b578f6217796ab059b",
          "sha256": "8c73241861ccb5259d6717da512cede58c590a8bdcfab882557efb6ddfedf74e",
          "sha1": "a3b979d4b24aa2f9d0b2173ae39fb88568ab9662",
          "md5": "5560e36104c106ee6db87fcab4bb5699"
        }
      ]
    }
  ]
}
