{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.asm",
    "module": "AsmPlugin",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "AsmPlugin-1.0.1.jar",
          "url": "AsmPlugin-1.0.1.jar",
          "size": 14230,
          "sha512": "0dc38a24c644f873921abe413f15411a2f67af6c69892495d473d7c765d79674f9619d78e78873f31ac5939ac34ed84e60494c809e14cb47ae5cfdb2fcf1b2f6",
          "sha256": "5c7b3a8782baaff0b3b87b1f4cb61f8b72b36c1b9892b8f630860041a315aedb",
          "sha1": "a38a983ae942e8c13e752994884ecda6c5373a28",
          "md5": "eb9102e75a66da8914abe422e85bff7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "AsmPlugin-1.0.1.jar",
          "url": "AsmPlugin-1.0.1.jar",
          "size": 14230,
          "sha512": "0dc38a24c644f873921abe413f15411a2f67af6c69892495d473d7c765d79674f9619d78e78873f31ac5939ac34ed84e60494c809e14cb47ae5cfdb2fcf1b2f6",
          "sha256": "5c7b3a8782baaff0b3b87b1f4cb61f8b72b36c1b9892b8f630860041a315aedb",
          "sha1": "a38a983ae942e8c13e752994884ecda6c5373a28",
          "md5": "eb9102e75a66da8914abe422e85bff7a"
        }
      ]
    }
  ]
}
